apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      imagePullSecrets:
        - name: my-gitlab-registry-sec
      containers:
        - name: httpd
          image: registry.gitlab.com/review11/ema-k8s-gitops/httpd:latest  
          ports:
            - containerPort: 80
